[pytest]
# Искать тесты СТРОГО внутри папки tests
testpaths = tests

# Игнорировать вообще ВСЕ папки, кроме папки tests при сканировании
norecursedirs = src venv .venv env .git .github .vscode .* build dist

# Явное правило: собирать тесты только из файлов, которые лежат в tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*